[versions]
accompanist-coil = "0.12.0"
accompanist-insets = "0.12.0"
androidx-junit = "1.1.5"
appcompat = "1.6.1"
arrow-core = "1.0.1"
clarity = "1.3.0"
crashlytics = "2.9.7"
activity-compose = "1.8.1"
compose-runtime = "1.5.4"
compose-ui = "1.5.4"
compose-ui-test-manifest = "1.5.4"
compose-compiler = "1.5.5"
navigation-compose = "2.7.5"
hilt-navigation-compose = "1.1.0"
converter-moshi = "2.9.0"
core-ktx = "1.12.0"
datastore-preferences = "1.0.0"
detekt = "1.19.0"
espresso-core = "3.5.1"
exoplayer = "2.15.0"
fastble = "2.4.0"
glide = "4.12.0"
google-material = "1.10.0"
google-services = "4.4.0"
gson = "2.10.1"
hilt-android = "2.48.1"
secrets-gradle-plugin = "2.0.1"

junit = "4.13.2"
kluent-android = "1.73"
kotlinx-coroutines-test = "1.7.1"
kotest = "5.5.4"
lifecycle-runtime-ktx = "2.6.2"
logging-interceptor = "4.9.2"
material = "1.5.4"
mockk = "1.12.4"
mockwebserver = "4.9.3"
moshi = "1.15.0"
okhttp3-idling-resource = "1.0.0"
palette = "1.0.0"
retrofit = "2.9.0"
robolectric = "4.10.3"
room-runtime = "2.6.1"
rssparser = "4.0.2"
turbine = "0.12.3"

[libraries]
accompanist-coil = { module = "com.google.accompanist:accompanist-coil", version.ref = "accompanist-coil" }
accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist-insets" }

activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore-preferences" }

lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-runtime-ktx" }
material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "material" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose-runtime" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose-ui" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose-ui" }

room-compiler = { module = "androidx.room:room-compiler", version.ref = "room-runtime" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room-runtime" }

arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow-core" }

clarity = { module = "com.microsoft.clarity:clarity", version.ref = "clarity" }

core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }

exoplayer = { module = "com.google.android.exoplayer:exoplayer", version.ref = "exoplayer" }
exoplayer-core = { module = "com.google.android.exoplayer:exoplayer-core", version.ref = "exoplayer" }
exoplayer-ui = { module = "com.google.android.exoplayer:exoplayer-ui", version.ref = "exoplayer" }

extension-mediasession = { module = "com.google.android.exoplayer:extension-mediasession", version.ref = "exoplayer" }
fastble = { module = "com.github.Jasonchenlijian:FastBle", version.ref = "fastble" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
google-material = { module = "com.google.android.material:material", version.ref = "google-material" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-android" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt-android" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }

lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "logging-interceptor" }
compose-material = { module = "androidx.compose.material:material", version.ref = "material" }

moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
moshi-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi" }
converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "converter-moshi" }

palette = { module = "androidx.palette:palette-ktx", version.ref = "palette" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
rssparser = { module = "com.prof18.rssparser:rssparser", version.ref = "rssparser" }

# Tests
junit = { module = "junit:junit", version.ref = "junit" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
kotest = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kluent = { module = "org.amshove.kluent:kluent", version.ref = "kluent-android" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-test" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }

# Android Tests
ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose-ui" }
kluent-android = { module = "org.amshove.kluent:kluent-android", version.ref = "kluent-android" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "mockwebserver" }
okhttp3-idling-resource = { module = "com.jakewharton.espresso:okhttp3-idling-resource", version.ref = "okhttp3-idling-resource" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt-android" }

# Debug
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose-ui-test-manifest" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-ui" }

[plugins]
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
